"""

Revision ID: 2a4ad6ac374b
Revises: 3d15a9e0775c
Create Date: 2026-02-21 17:00:36.595296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2a4ad6ac374b'
down_revision: Union[str, None] = '3d15a9e0775c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobookserieslink',
    sa.Column('audiobook_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_asin'], ['audiobook.asin'], ),
    sa.ForeignKeyConstraint(['series_asin'], ['series.asin'], ),
    sa.PrimaryKeyConstraint('audiobook_asin', 'series_asin')
    )
    op.drop_table('audiobook_series_link')
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_client_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.drop_column('download_client_hash')

    op.create_table('audiobook_series_link',
    sa.Column('audiobook_asin', sa.VARCHAR(), nullable=False),
    sa.Column('series_asin', sa.VARCHAR(), nullable=False),
    sa.Column('sequence', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_asin'], ['audiobook.asin'], ),
    sa.ForeignKeyConstraint(['series_asin'], ['series.asin'], ),
    sa.PrimaryKeyConstraint('audiobook_asin', 'series_asin')
    )
    op.drop_table('audiobookserieslink')
    # ### end Alembic commands ###
