"""

Revision ID: 2fc699b9cba7
Revises: a43ab48f5583
Create Date: 2026-02-20 23:11:14.583160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '2fc699b9cba7'
down_revision: Union[str, None] = 'a43ab48f5583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('series',
    sa.Column('asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('save_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('asin')
    )
    op.create_table('audiobook_series',
    sa.Column('audiobook_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_asin'], ['audiobook.asin'], ),
    sa.ForeignKeyConstraint(['series_asin'], ['series.asin'], ),
    sa.PrimaryKeyConstraint('audiobook_asin', 'series_asin')
    )
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.drop_column('series')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series', sqlite.JSON(), nullable=True))

    op.drop_table('audiobook_series')
    op.drop_table('series')
    # ### end Alembic commands ###
