"""

Revision ID: 33241b88a192
Revises: 2a4ad6ac374b
Create Date: 2026-02-28 23:05:50.516810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '33241b88a192'
down_revision: Union[str, None] = '2a4ad6ac374b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('save_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('asin')
    )
    op.create_table('audiobookauthorlink',
    sa.Column('audiobook_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_asin'], ['audiobook.asin'], ),
    sa.ForeignKeyConstraint(['author_asin'], ['author.asin'], ),
    sa.PrimaryKeyConstraint('audiobook_asin', 'author_asin')
    )
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.drop_column('authors')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sqlite.JSON(), nullable=True))

    op.drop_table('audiobookauthorlink')
    op.drop_table('author')
    # ### end Alembic commands ###
