"""

Revision ID: 3d15a9e0775c
Revises: 2fc699b9cba7
Create Date: 2026-02-21 16:39:22.831877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d15a9e0775c'
down_revision: Union[str, None] = '2fc699b9cba7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobook_series_link',
    sa.Column('audiobook_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_asin'], ['audiobook.asin'], ),
    sa.ForeignKeyConstraint(['series_asin'], ['series.asin'], ),
    sa.PrimaryKeyConstraint('audiobook_asin', 'series_asin')
    )
    op.drop_table('audiobook_series')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audiobook_series',
    sa.Column('audiobook_asin', sa.VARCHAR(), nullable=False),
    sa.Column('series_asin', sa.VARCHAR(), nullable=False),
    sa.Column('sequence', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_asin'], ['audiobook.asin'], ),
    sa.ForeignKeyConstraint(['series_asin'], ['series.asin'], ),
    sa.PrimaryKeyConstraint('audiobook_asin', 'series_asin')
    )
    op.drop_table('audiobook_series_link')
    # ### end Alembic commands ###
