"""

Revision ID: 842e3f1db429
Revises: d0fac85afd0f
Create Date: 2026-03-02 00:45:51.337775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '842e3f1db429'
down_revision: Union[str, None] = 'd0fac85afd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('save_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asin'),
    sa.UniqueConstraint('name')
    )
    op.create_table('series',
    sa.Column('asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('save_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('asin')
    )
    op.create_table('audiobookauthorlink',
    sa.Column('audiobook_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['audiobook_asin'], ['audiobook.asin'], ),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('audiobook_asin', 'author_id')
    )
    op.create_table('audiobookserieslink',
    sa.Column('audiobook_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('series_asin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sequence', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['audiobook_asin'], ['audiobook.asin'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_asin'], ['series.asin'], ),
    sa.PrimaryKeyConstraint('audiobook_asin', 'series_asin')
    )
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('download_progress', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('download_client_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.drop_column('authors')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors', sqlite.JSON(), nullable=True))
        batch_op.drop_column('download_client_hash')
        batch_op.drop_column('download_progress')

    op.drop_table('audiobookserieslink')
    op.drop_table('audiobookauthorlink')
    op.drop_table('series')
    op.drop_table('author')
    # ### end Alembic commands ###
