"""Download Client Metadata

Revision ID: a43ab48f5583
Revises: d0fac85afd0f
Create Date: 2026-02-20 12:39:53.389618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a43ab48f5583'
down_revision: Union[str, None] = 'd0fac85afd0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.add_column(sa.Column('series', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('download_progress', sa.Integer(), nullable=False, default=0))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audiobook', schema=None) as batch_op:
        batch_op.drop_column('download_progress')
        batch_op.drop_column('series')

    # ### end Alembic commands ###
